name: 'student_scores'
version: '1.0.0'
config-version: 2

profile: 'loopcapital'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  student_scores:
    staging:
      +materialized: view
      +tags:
        - staging
        - student_scores
    marts:
      +materialized: table
      +tags:
        - marts
        - student_scores
